name: ci
on:
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 10.15.3

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v3
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install
      run: yarn --frozen-lockfile

    - name: Lint
      run: yarn lint

    - name: Test
      run: yarn test

    - name: Build
      run: yarn build
