# This is a basic workflow to help you get started with Actions

name: Release
on:
  push:
    branches:
      - master
      
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: node-red-contrib-neopixel-display
      - uses: actions/checkout@v4
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v3
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}
      - run: yarn install --frozen-lockfile
        if: ${{ steps.release.outputs.release_created }}
      - run: yarn build
        if: ${{ steps.release.outputs.release_created }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
